package.path = "../src/?.lua;./?.lua;" .. package.path

local T = require("test_helper")
require("unit_board_test")
require("unit_game_logic_test")
require("unit_game_over_layout_test")
require("unit_game_guide_test")
require("unit_app_info_test")
require("unit_pagination_test")
require("integration_controller_test")
require("integration_autoplay_test")
require("boundary_test")
require("white_box_test")
require("unit_services_test")
require("integration_app_test")
require("unit_input_adapter_test")
require("unit_global_leaderboard_test")
require("unit_auth_session_test")
require("unit_account_identity_test")
require("integration_lifecycle_test")
require("security_privacy_test")
T.finish()
